name: Update README 

on:
  push:
    branches:
    - master
    paths-ignore:
    - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Display the path
      run: |-
        ./update-readme.md
        cat README.asc
      shell: pwsh
