name: Update README 

on:
  push:
    branches:
    - master
    paths-ignore:
    - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Update README.asc
      run: |-
        ./update-readme.ps1
        cat README.asc
      shell: pwsh
    - name: Commit and push if README.asc was updated
      run: |-
        git diff
        git config --global user.email "githubactions@example.com"
        git config --global user.name "GitHub Actions"
        git diff --quiet || (git add README.asc && git commit -m "Updated README")